spring.application.name=lab1
server.port=8080

spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:55413/railway
spring.datasource.username=postgres
spring.datasource.password=GZATdlWGTyyeCKbaIzFzcJhBfBecMcgD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=50